### PR TITLE
Allow easy access to the transports layers

### PR DESCRIPTION
**Pull request by rhomspuron**
Allow to access to the device transports layers and remove the URL as mandatory parameter to create easy test with pytest.

### CODE REVIEW

**Comment by tiagocoutinho** [comment]
@rhomspuron,

Right now, the "name" is not a mandatory keyword and it defaults to the the device class name.

This means that if you declare two devices of the same class in the config file without giving them a name, the content of `dev_transport` only stores the last device declared the config file.

Since this may lead to confusing behaviour I propose that we make the "name" of each device a mandatory and unique property.
What do you think?

**Comment by rhomspuron** [comment]
@tiagocoutinho this is a good idea.

**Comment by tiagocoutinho** [comment]
@rhomspuron,
Then I made a commit here where I make the "name" mandatory". 
Now if you have a reference to the server you can get the list of transports for a device with something like:

```python
server.devices["mydevice"].transports
```
is that ok for you?

**Comment by rhomspuron** [comment]
Yes, it is OK. Thanks!

**Comment by tiagocoutinho** [comment]
Great, merging!

**Pull request merged**
